version: "3"

tasks:
  # Menjalankan development mode
  dev:
    desc: "Jalankan aplikasi Go (Development Mode)"
    cmds:
      # - go run main.go
      # Jika Anda menggunakan 'air' untuk hot-reload, gunakan baris di bawah ini dan hapus 'go run main.go'
      - air

  # Build aplikasi menjadi binary
  build:
    desc: "Build aplikasi Go"
    cmds:
      # Membuat folder bin/ jika belum ada (Task otomatis menangani ini di Windows/Linux)
      - mkdir -p bin
      - go build -o bin/app.exe main.go

  # Menjalankan docker compose (Postgres & Redis)
  up:
    desc: "Jalankan container Docker Compose"
    cmds:
      - docker compose up -d

  # Menghentikan docker compose
  down:
    desc: "Hentikan container Docker Compose"
    cmds:
      - docker compose down

  # Menjalankan build dan docker compose sekaligus
  start:
    desc: "Jalankan database dan jalankan aplikasi"
    deps: [up] # Memastikan docker up jalan lebih dulu
    cmds:
      - go run main.go
